project_id: dev-intern-poc
billing_account: "01783B-A7A65B-153181"
labels:
  environment: dev
  owner: intern
apis:
  - run.googleapis.com
resources:
  cloud_run_services:
    - name: hello-run
      location: us-central1
      image: nginxinc/nginx-unprivileged:stable-alpine
      allow_unauthenticated: true
