# Example project configuration
project_id: "dev-intern-poc-test13"
# Existing Organization ID (optional) if not provided, the project will be created in the root organization
organization_id: null
# Existing Billing Account ID (null for personal accounts)
billing_account: null

labels:
  owner: "intern"
  environment: "test"

apis:
  - compute.googleapis.com
  - iam.googleapis.com
