# Example project configuration
project_id: "dev-intern-poc"
# Existing Organization ID
organization_id: null
# Existing Billing Account ID
billing_account: "01783B-A7A65B-153181"

labels:
  owner: "intern"
  environment: "test"

apis:
  - compute.googleapis.com
  - iam.googleapis.com
