# Project A -  Bucket
project_id: "canvas-setup-457316-b2"
organization_id: null
billing_account: "01783B-A7A65B-153181"

labels:
  owner: "intern"
  environment: "dev"

apis:
  - compute.googleapis.com
  - iam.googleapis.com
  - storage.googleapis.com

resources:
  storage_buckets:
    - name: "dev-intern-proj-a-logs-here"
      location: "US"
      enable_versioning: true
      labels: { purpose: "logs" }
