# Service Account Example Configuration
project_id: "dev-intern-poc"
organization_id: null
billing_account: "01783B-A7A65B-153181"

labels:
  owner: "intern"
  environment: "dev"
  purpose: "service-account-demo"

apis:
  - iam.googleapis.com
  - storage.googleapis.com
  - pubsub.googleapis.com
  - compute.googleapis.com
  - sqladmin.googleapis.com

resources:
  # Service Accounts for different purposes
  service_accounts:
    # Web Application Service Account
    - account_id: "web-app-service"
      display_name: "Web Application Service Account"
      description: "Service account for web application operations and API access"

    # Database Service Account
    - account_id: "database-service"
      display_name: "Database Service Account"
      description: "Service account for database connections and operations"

    # CI/CD Pipeline Service Account
    - account_id: "cicd-pipeline"
      display_name: "CI/CD Pipeline Service Account"
      description: "Service account for continuous integration and deployment"

    # Monitoring Service Account
    - account_id: "monitoring-agent"
      display_name: "Monitoring Agent Service Account"
      description: "Service account for monitoring, logging, and metrics collection"

    # Storage Service Account
    - account_id: "storage-service"
      display_name: "Storage Service Account"
      description: "Service account for file storage operations and backups"

    # Pub/Sub Service Account
    - account_id: "pubsub-service"
      display_name: "Pub/Sub Service Account"
      description: "Service account for message publishing and subscription"

    # Compute Service Account
    - account_id: "compute-service"
      display_name: "Compute Service Account"
      description: "Service account for VM and container operations"

    # Security Service Account
    - account_id: "security-service"
      display_name: "Security Service Account"
      description: "Service account for security scanning and compliance checks"

    # Analytics Service Account
    - account_id: "analytics-service"
      display_name: "Analytics Service Account"
      description: "Service account for data analytics and reporting"

    # Backup Service Account
    - account_id: "backup-service"
      display_name: "Backup Service Account"
      description: "Service account for automated backup operations"

  # IAM Bindings to assign roles to service accounts
  iam_bindings:
    # Web App Service Account Permissions
    - role: "roles/storage.objectViewer"
      member: "serviceAccount:web-app-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow web app to read storage objects"

    - role: "roles/pubsub.subscriber"
      member: "serviceAccount:web-app-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow web app to subscribe to Pub/Sub topics"

    # Database Service Account Permissions
    - role: "roles/cloudsql.client"
      member: "serviceAccount:database-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow database service to connect to Cloud SQL"

    - role: "roles/cloudsql.instanceUser"
      member: "serviceAccount:database-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow database service to use Cloud SQL instances"

    # CI/CD Pipeline Service Account Permissions
    - role: "roles/cloudbuild.builds.builder"
      member: "serviceAccount:cicd-pipeline@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow CI/CD to build and deploy applications"

    - role: "roles/container.developer"
      member: "serviceAccount:cicd-pipeline@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow CI/CD to manage containers"

    - role: "roles/storage.admin"
      member: "serviceAccount:cicd-pipeline@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow CI/CD to manage storage buckets"

    # Monitoring Service Account Permissions
    - role: "roles/monitoring.metricWriter"
      member: "serviceAccount:monitoring-agent@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow monitoring agent to write metrics"

    - role: "roles/logging.logWriter"
      member: "serviceAccount:monitoring-agent@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow monitoring agent to write logs"

    - role: "roles/monitoring.viewer"
      member: "serviceAccount:monitoring-agent@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow monitoring agent to view monitoring data"

    # Storage Service Account Permissions
    - role: "roles/storage.objectAdmin"
      member: "serviceAccount:storage-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow storage service to manage objects"

    - role: "roles/storage.legacyBucketReader"
      member: "serviceAccount:storage-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow storage service to read bucket metadata"

    # Pub/Sub Service Account Permissions
    - role: "roles/pubsub.publisher"
      member: "serviceAccount:pubsub-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow Pub/Sub service to publish messages"

    - role: "roles/pubsub.subscriber"
      member: "serviceAccount:pubsub-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow Pub/Sub service to subscribe to topics"

    - role: "roles/pubsub.admin"
      member: "serviceAccount:pubsub-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow Pub/Sub service to manage topics and subscriptions"

    # Compute Service Account Permissions
    - role: "roles/compute.instanceAdmin"
      member: "serviceAccount:compute-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow compute service to manage VM instances"

    - role: "roles/compute.networkAdmin"
      member: "serviceAccount:compute-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow compute service to manage network resources"

    # Security Service Account Permissions
    - role: "roles/securitycenter.findingsEditor"
      member: "serviceAccount:security-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow security service to manage security findings"

    - role: "roles/cloudasset.viewer"
      member: "serviceAccount:security-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow security service to view cloud assets"

    # Analytics Service Account Permissions
    - role: "roles/bigquery.dataViewer"
      member: "serviceAccount:analytics-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow analytics service to view BigQuery data"

    - role: "roles/bigquery.jobUser"
      member: "serviceAccount:analytics-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow analytics service to run BigQuery jobs"

    # Backup Service Account Permissions
    - role: "roles/storage.objectAdmin"
      member: "serviceAccount:backup-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow backup service to manage backup objects"

    - role: "roles/compute.storageAdmin"
      member: "serviceAccount:backup-service@dev-intern-poc.iam.gserviceaccount.com"
      description: "Allow backup service to manage compute storage"

  # Storage Buckets for testing service account access
  storage_buckets:
    - name: "web-app-assets-bucket"
      location: "US"
      labels:
        purpose: "web-assets"
        service: "web-app"

    - name: "backup-storage-bucket"
      location: "US"
      labels:
        purpose: "backups"
        service: "backup-service"

  # Pub/Sub Topics for testing service account access
  pubsub_topics:
    - name: "web-app-events"
      labels:
        service: "web-app"
        purpose: "events"

    - name: "monitoring-alerts"
      labels:
        service: "monitoring"
        purpose: "alerts"
