name: Infrastructure Deploy

# Workflow to deploy infrastructure when commit contains 'deploy'
on:
  # Trigger on any push for testing
  push:
    branches:
      - main
  # Manual trigger
  workflow_dispatch:
    inputs:
      yaml_file:
        description: "YAML file to deploy"
        required: true
        default: "configs/example-project.yaml"

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.PERSONAL_GCP_CREDENTIALS }}' > /tmp/credentials.json
          gcloud config set project konecta-task-1-hands-on

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Get YAML files to process
        id: yaml-files
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "files=${{ github.event.inputs.yaml_file }}" >> $GITHUB_OUTPUT
          else
            # Find all YAML files in configs directory
            echo "files=$(find configs -name '*.yaml' -o -name '*.yml' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          fi

      - name: Deploy infrastructure
        run: |
          for file in ${{ steps.yaml-files.outputs.files }}; do
            if [ -f "$file" ]; then
              echo "🚀 Deploying infrastructure for: $file"
              python scripts/deploy.py "$file"
            fi
          done

      - name: Send Slack Notification on Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚀 Infrastructure Deployed Successfully! Repository: ${{ github.repository }} Branch: ${{ github.ref_name }} Commit: ${{ github.sha }} Files: ${{ steps.yaml-files.outputs.files }} Actor: ${{ github.actor }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack Notification on Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Infrastructure Deployment Failed! Repository: ${{ github.repository }} Branch: ${{ github.ref_name }} Commit: ${{ github.sha }} Files: ${{ steps.yaml-files.outputs.files }} Actor: ${{ github.actor }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on Success
        if: success()
        run: |
          echo "✅ Infrastructure deployment completed successfully!"
          echo "Files: ${{ steps.yaml-files.outputs.files }}"
          echo "::notice::Infrastructure deployed successfully for: ${{ steps.yaml-files.outputs.files }}"

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Infrastructure deployment failed!"
          echo "Files: ${{ steps.yaml-files.outputs.files }}"
          echo "::error::Infrastructure deployment failed for: ${{ steps.yaml-files.outputs.files }}"
