name: Infrastructure Deploy/Destroy

on:
  workflow_dispatch:
    inputs:
      action:
        description: deploy or destroy
        required: true
        default: deploy
      files:
        description: space-separated YAML paths (e.g., configs/a.yaml configs/b.yaml)
        required: true
      approve:
        description: yes to auto-apply / non-interactive
        required: true
        default: "no"

permissions:
  contents: write

jobs:
  infra:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Configure ADC with personal credentials
        env:
          PERSONAL: ${{ secrets.PERSONAL_GCP_CREDENTIALS }}
        shell: bash
        run: |
          set -euo pipefail
          CREDS="$RUNNER_TEMP/creds.json"
          printf '%s' "$PERSONAL" > "$CREDS"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$CREDS" >> $GITHUB_ENV
          echo "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=$CREDS" >> $GITHUB_ENV

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Parse workflow inputs
        id: parse
        shell: bash
        run: |
          set -euo pipefail
          ACTION="${{ github.event.inputs.action }}"
          APPROVE="${{ github.event.inputs.approve }}"
          FILES="${{ github.event.inputs.files }}"

          echo "action=$ACTION" >> $GITHUB_OUTPUT
          echo "approve=$APPROVE" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT
          printf "Parsed action='%s' approve='%s' files=\n%s\n" "$ACTION" "$APPROVE" "$FILES"

      - name: Show plan-only note for destroy without approve
        if: steps.parse.outputs.action == 'destroy' && steps.parse.outputs.approve != 'yes'
        run: |
          echo "Destroy requires approve=yes. Skipping destructive run."
          exit 0

      - name: Run deploy (plan-only unless approve=yes)
        if: steps.parse.outputs.action == 'deploy'
        shell: bash
        run: |
          set -euo pipefail
          # Ensure .tf-runs directory exists
          mkdir -p .tf-runs
          echo "Created .tf-runs directory"

          FILES=( ${{ steps.parse.outputs.files }} )
          if [[ "${{ steps.parse.outputs.approve }}" == "yes" ]]; then
            # auto-approve applies by piping yes
            yes | python scripts/deploy.py "${FILES[@]}"
          else
            # ensure plan-only by piping no responses
            yes no | python scripts/deploy.py "${FILES[@]}" || true
          fi

      - name: Run destroy (modules by default; add 'project' in commit to delete project)
        if: steps.parse.outputs.action == 'destroy' && steps.parse.outputs.approve == 'yes'
        shell: bash
        run: |
          set -euo pipefail
          # Ensure .tf-runs directory exists
          mkdir -p .tf-runs
          echo "Created .tf-runs directory"

          FILES=( ${{ steps.parse.outputs.files }} )
          MSG="${{ github.event.head_commit.message }}"
          CHOICE=m
          shopt -s nocasematch
          [[ "$MSG" =~ project ]] && CHOICE=p || true
          shopt -u nocasematch
          # feed: yes then choice m/p
          { echo yes; echo "$CHOICE"; } | python scripts/destroy.py "${FILES[@]}"

      - name: Persist .tf-runs into repo
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          echo "Current directory: $(pwd)"
          echo "Contents of .tf-runs:"
          ls -la .tf-runs/ || echo "No .tf-runs directory found"
          if [ -d ".tf-runs" ]; then
            echo "Contents of .tf-runs subdirectories:"
            find .tf-runs -type f -name "*.tf" -o -name "*.json" | head -20
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add only Terraform source files, not .terraform directory
          if [ -d ".tf-runs" ]; then
            # Add .tf and .json files but exclude .terraform directory
            find .tf-runs -name "*.tf" -o -name "*.json" | grep -v ".terraform" | xargs git add -f
            echo "Added Terraform source files to git (excluding .terraform directory)"
          else
            echo "No .tf-runs directory to add"
          fi

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "CI: persist tf state for ${{ steps.parse.outputs.files }} (action=${{ steps.parse.outputs.action }}, approve=${{ steps.parse.outputs.approve }})"
            echo "Committed changes"
            git push
            echo "Pushed changes to remote"
          fi

      - name: Notify Slack (success)
        if: success()
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          if [[ -z "${SLACK_WEBHOOK_URL:-}" ]]; then exit 0; fi
          ACTION='${{ steps.parse.outputs.action }}'
          APPROVE='${{ steps.parse.outputs.approve }}'
          FILES='${{ steps.parse.outputs.files }}'
          REPO='${{ github.repository }}'
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MSG="✅ Infra ${ACTION} (approve=${APPROVE}) succeeded for ${FILES} in ${REPO}. <${RUN_URL}|Run details>"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MSG//\"/\\\"}\"}" "$SLACK_WEBHOOK_URL" || true

      - name: Notify Slack (failure)
        if: failure()
        shell: bash
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          if [[ -z "${SLACK_WEBHOOK_URL:-}" ]]; then exit 0; fi
          ACTION='${{ steps.parse.outputs.action }}'
          APPROVE='${{ steps.parse.outputs.approve }}'
          FILES='${{ steps.parse.outputs.files }}'
          REPO='${{ github.repository }}'
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          MSG="❌ Infra ${ACTION} (approve=${APPROVE}) failed for ${FILES} in ${REPO}. <${RUN_URL}|Run details>"
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MSG//\"/\\\"}\"}" "$SLACK_WEBHOOK_URL" || true
